### ISSUE TITLE
Make TemplateHaskell brackets polymorphic in the monad

### ISSUE THREAD

**Issue by int-index** [ghc-proposals/ghc-proposals#211]
We have `[| blah |] :: Q Exp`, but we don't have to, – it could be `Monad m => m Exp`, or even `Applicative f => f Exp`.

Brackets desugar to functions from `Language.Haskell.TH.Lib`, and I suspect we could achieve this by changing the type signatures there. Take `parensE` for instance, it's defined as

```
parensE :: ExpQ -> ExpQ
parensE x = do { x' <- x; return (ParensE x') }
```

but it might as well be

```
parensE :: Functor f => f Exp -> f Exp
parensE = fmap ParensE
```

Here, even `Functor` is sufficient! But we would need `Applicative` for combinators that use `sequence`.

----

Why do this? Because now it's possible to extract the quoted expression without running `Q`, by doing `runIdentity [| blah |] :: Exp`.

**Comment by RyanGlScott** [comment]
It's worth noting that it's not always possible to support just a `Monad` constraint. Here's a problematic example:

```haskell
[t| forall a. a |]
```

If you inspect the code that this splices in with `-ddump-simpl`, you'll see:

```
λ> :set -ddump-simpl -XTemplateHaskell -XRankNTypes 
λ> :k $([t| forall a. a |])

==================== Simplified expression ====================
Language.Haskell.TH.Syntax.bindQ
  @ Language.Haskell.TH.Syntax.Name
  @ Language.Haskell.TH.Syntax.Type
  (Language.Haskell.TH.Syntax.newName
     (GHC.CString.unpackCString# "a"#))
  (\ (a_a4pN :: Language.Haskell.TH.Syntax.Name) ->
     Language.Haskell.TH.Lib.Internal.forallT
       (GHC.Types.:
          @ Language.Haskell.TH.Lib.Internal.TyVarBndrQ
          (Language.Haskell.TH.Lib.Internal.plainTV a_a4pN)
          (GHC.Types.[] @ Language.Haskell.TH.Lib.Internal.TyVarBndrQ))
       (Language.Haskell.TH.Lib.Internal.cxt
          (GHC.Types.[] @ Language.Haskell.TH.Lib.Internal.TypeQ))
       (Language.Haskell.TH.Lib.Internal.varT a_a4pN))
```

After some cleanup, that's:

```haskell
newName "a" >>= \a -> forallT (plainTV a) (cxt []) (varT a)
```

Note the use of `newName`. We could generalize that to use `qNewName :: Quasi m => String -> m Name`, but that requires `Quasi`, which is less general than `Monad` is. In particular, there is no `Quasi Identity` instance.

That's not to say that this idea doesn't have merit. There are certain situations where the inferred type of a bracket could very well be generalized to `Monad` or `Applicative`. But we'd have to be careful about what we guarantee, because unless I'm overlooking something, there are certain situations where `Quasi` is unavoidable.

**Comment by int-index** [comment]
@RyanGlScott Name generation is a much weaker constraint than `Quasi`. `newName :: String -> m Name` can be implemented with `m ~ State Int`, appending a fresh number to each string.

**Comment by RyanGlScott** [comment]
True. The high-level bit is that this proposal may involve more than just "changing the type signatures" if your goal is to make `Monad` the most specific constraint that is ever inferred for the return type of a bracket.

Another thing you'd have to generalize is `lift` (whose return type is currently hard-coded to `Q`), since brackets can desugar to code mentioning `lift` as well.

**Comment by mpickering** [comment]
@RyanGlScott The mention of lift is not really to do with brackets but to do with splices. So you observation is that you also need to overload splices.

Also see #195 and https://gitlab.haskell.org/ghc/ghc/issues/16178 for some more discussion.

**Comment by goldfirere** [comment]
I somehow missed this when it first came up... I support this direction of generalization, but we have to be careful as to what we can guarantee. Maybe the constraint can be something like `MonadState Int m` (or a `MonadSerial m` or something).

Actually, we can do better, I think.

I've done a fairly brief audit about the uses of `Q`. Here is what I have found. (This was brief and unscientific. I may be wrong.)
 - Of the functions mentioned in THNames, only 5 make interesting use of `Q`. By "interesting", I mean they invoke actions other than things like `fmap`, `sequence`, `>>=`, etc. (Is it right to say that "interesting" actions are ones that would not be in a free monad? Never quite felt comfortable with free monads.)
 - `newName`: This is important and is expanded upon below.
 - `lift`: Why is `lift` in the `Q` monad? Unless I missed something, the code produced by `deriving Lift` does not invoke any `Q`-specific actions (not even `newName`). Maybe some hand-written instances do? Is there ever a concrete need for hand-written instances that need `Q` though?
 - `unTypeQ` and `unsafeTExpCoerce`: These are only about typed TH. Let's tackle untyped TH first. It is reasonable (though suboptimal) to put untyped brackets in a different monad than typed ones.
 - `Language.Haskell.TH.Lib.Internal.numTyLit` calls `fail`. I think changing to `error` is a reasonable way forward.

About `newName`: this is used to create gensyms during quote desugaring. The idea is that a variable bound in a quotation should be distinguished from all other variables. To accomplish this, GHC uses `newName` to freshen the variable at splice time.

However, could we do this at *quotation time* instead? The challenge is that we want a guaranteed-fresh name. At quotation time, this is actually easy: we have the `Unique` GHC has assigned the name. Squeeze that `Unique` into a format usable in TH (like an `Int`), and then we can make a new flavor of `TH.Name` that carries that `Unique` with it. The problem is that such a name might perchance be captured if the same quotation is used more than once. Here is an example:

```
q n = [| let x = n in x |]

z = $( do LetE binds1 body1 <- q 5
          LetE binds2 body2 <- q 6
          LetE (binds1 ++ binds2) <$> [| $(return body1) + $(return body2) |] )
```

(These are in different files because of the stage restriction.) In GHC today, `z` evaluates to `11`. This is because the two calls to `q` run `newName` independently, and thus the two `x`s are distinguishable. If we use my approach of disambiguating at *quotation time* instead of *splice time*, then `z` would be `12`, because the inner `x` would shadow the outer one. Would this change in behavior ever be noticed in the wild? I don't know.

If we are willing to consider changing this semantics of TH to move uniqueness guarantees to *quotation time* instead of *splice time*, then *we don't need a monad at all*. (Also, we need to move `lift` out of `Q`, too.)

Of course, I've skipped one important scenario: the use of a splice inside of a quotation. If splices are still to use `Q` (and indeed that's very useful), then we need a new rule: if a quotation mentions a splice, then that quotation is in the `Q` monad. If it doesn't mention a splice, then it isn't.

Backward compatibility: my scheme of having `[| blah |] :: Exp` will break lots and lots of code. So let's not. Instead, call this a support of the original proposal to generalize `[| blah |]` to have type `Applicative f => f Exp` where we need `Applicative` so that we have `pure`.

Open question: can we move `lift` out of the `Q` monad?

**Comment by mpickering** [comment]
I agree with most of what you are saying Richard apart from a few things. I did my own personal audit and discovered what you did about `newName` a while ago whilst talking about this with @int-index .

1. Not also dealing with typed template haskell at the same time is unacceptable.
2. I imagine some programs will break if name generation is moved to compile time but only ones which inspect the syntax in the way you describe which is dubious anyway. 
3. `lift` isn't in the Q monad? But if quotes are generalised then the type of `lift` will have to be as well. This means user written instances will be broken but people should use `DeriveLift` anyway. We could also just solve `Lift` instances automatically for users like we do for `Typeable`.
4. The splice form should also be overloaded I think? As otherwise if you don't use `f = Q` then you will have to insert weakening functions everywhere.
5. Why do we need the `Applicative` constraint? Should there rather be a custom class like there is for `StaticPointers`?

**Comment by int-index** [comment]
> If we are willing to consider changing this semantics of TH to move uniqueness guarantees to quotation time instead of splice time, then we don't need a monad at all.

I'm very uncomfortable with this suggestion, although I see its appeal. The current design makes it harder to accidentally create a name collision, and getting rid of an applicative context is poor rationale for moving in the opposite direction. What's wrong with `MonadSerial`?

**Comment by mpickering** [comment]
@int-index If you are doing things like @goldfirere suggests and combining together let bindings in this ad-hoc manner then you have no guarantee anyway that the code you produce will be correct as there is no guarantee about how the names were produced.

However, I think `MonadSerial` is fine as it gives people the choice about how to control name generation. If everything is overloaded then a user can provide an instance for `IsBracket` which immediately runs the effect leave a pure bracket, otherwise if they don't immediately run the effect then programs like Richard suggests will work properly still as the effects will be sequenced.

**Comment by michaelpj** [comment]
Since we're talking about relaxing the constraints on TH: one recurring bugbear with TH is cross-compilation. At the moment splices need to be run on the target, since they can do arbitrary IO via `Q`, which leads to the whole `iserv` dance. 

But many splices are entirely "pure", e.g. most things using typed TH. In the presence of a hypothetical `-XPureTemplateHaskell` we could allow only pure splices and run them on the host instead (at the cost of needing a host-to-host GHC and host-compiled dependencies). Non-trivial, but potentially a *lot* easier than having to have a running target around.

Moving things like `newName` into a superclass of `Q`/`Quasi` would be a great step in that direction.

**Comment by goldfirere** [comment]
Various responses:

1. When I deferred typed TH, I meant to consider the design questions independently, as an effort to reduce cognitive burden. I agree that the final design and implementation needs to account for typed TH. But perhaps if we design one and then the other, we'll get to a better place.
2. You're right, of course, that `lift` isn't in `Q`. What I meant is that the type of `lift` mentions `Q`, as it seems you surmised. My open question asks whether hand-written instances of `Lift` use `Q`-specific functionality in order to implement `lift`.
3. Getting rid of the monad makes quotes easier to work with. That's worth something to me.
4. `MonadSerial` is problematic in that it doesn't exist yet. And I feel that this one use case is too small to necessitate making it. Remember that the monad transformer design pattern is quadratic in nature.
5. I like the idea of a pure TH. Not only for cross-compilation, but also for safety. Whenever I think about compiling an untrusted codebase, TH gives me the willies. I wonder if a pure TH could be `-XSafe`.

**Comment by int-index** [comment]
> Getting rid of the monad makes quotes easier to work with. That's worth something to me.

With flimsy rules like this one, I doubt it:

>  if a quotation mentions a splice, then that quotation is in the `Q` monad. If it doesn't mention a splice, then it isn't.

What I had in mind is that a quotation is always in some monad `m` with constraints `c1 m`, and splices are in some monad `m` with constraints `c2 m`. A quotation that mentions a splice inherits its constraints on the monad:

```
f :: Quasi m => m Exp
g :: MonadIO m => m Exp
[| putStrLn $(f) >> putStrLn $(g) |] :: (Applicative m, Quasi m, MonadIO m) => m Exp
```

> Remember that the monad transformer design pattern is quadratic in nature.

We don't need transformers for this, just a single layer (which could be `Q`, `IO`, `State NameSupply`, or even `Identity` when no name generation is involved).

**Comment by goldfirere** [comment]
I like that last approach. But how do we identify when no name-generation is involved?

**Comment by int-index** [comment]
When name generation is involved, it adds a `MonadState NameSupply` or `MonadSerial` or a similar constraint.

**Comment by goldfirere** [comment]
Yes, but when is that: we must specify the conditions for name generation. Is it whenever the quote binds a variable (i.e. a `let` or a `forall` or ...)? I just want this to be clear and predictable.

**Comment by int-index** [comment]
Ah, of course. I think the implementation will reveal the specific places that require `newName` calls to preserve today's semantics. `let` and `forall` are obvious candidates.

**Comment by Ericson2314** [comment]
I just wanted to throw out that fresh names to me always seemed to weak a goal for Q. The gold standard for macro systems is traditionally custom binding constructs. http://www.cs.utah.edu/plt/scope-sets/ is the better known paper for this sort of thing, but I'm fond of https://cs.brown.edu/~sk/Publications/Papers/Published/pkw-inf-scope-syn-sugar/.

This is all clearly research out of scope of this issue, but I just wanted to make sure we leave enough `m`s, be they merely `Applicative m` or something more constrained, that this wouldn't be too much of a breaking change later. That seems to be where the consensus is anyways, but just wanted to be sure :).

**Comment by goldfirere** [comment]
Ping.

There is some good conversation here. Is there a conclusion? Should this become a proposal? Does this need a vote? It's all paged out for me, but I want some direction from @int-index before paging it back in.

**Comment by int-index** [comment]
> Should this become a proposal?

Yes, I'd be happy if someone turned this into a proposal.

>  Is there a conclusion?

Everyone seems content with the design I outlined in https://github.com/ghc-proposals/ghc-proposals/issues/211#issuecomment-472992179. To recap:

1. quotations and splices are generalized from using `Q` to using an abstract monad `m` with constraints `(c1 m, c2 m, c3 m, ...)`
2. a quotation that contains a splice inherits its constraints on the monad:
    ```
    f :: Quasi m => m Exp
    g :: MonadIO m => m Exp
    [| putStrLn $(f) >> putStrLn $(g) |] :: (Applicative m, Quasi m, MonadIO m) => m Exp
    ```
3. most combinators will only require `Applicative m` or weaker to combine the constituents:
    ```
    appE :: Applicative f => f Exp -> f Exp -> f Exp
    parensE :: Functor f => f Exp
    ```
4. for quotations that require name generation (`forall`, `let`, etc), we move `newName :: String -> Q Name` into a new class:
    ```
    class Applicative f => NameGen f where
      newName :: String -> f Name
    ```
    This is weaker than `Q` and can be implemented via some sort of `State NameSupply`.

**Comment by cartazio** [comment]
The real issue is that even with pure  th you have the problem that Int and
word could have different sizes on host vs target

**Comment by Ericson2314** [comment]
@cartazio I will (finally!) write a stage-separated TH proposal soon. It will dovetail nicely with that so I rather have two independent proposals.

**Comment by Ericson2314** [comment]
https://github.com/ghc-proposals/ghc-proposals/pull/204 will also dovetail nicely because I'll probably need to temporary disable typed TH and lifting pending further research, which removes the only impediments to that proposal.

**Comment by mpickering** [comment]
I will write this proposal seeing as it was my idea originally.

**Comment by Ericson2314** [comment]
https://github.com/ghc-proposals/ghc-proposals/pull/246 proposal is here.

**Comment by int-index** [comment]
Closing the issue as it's superceded by #246
