### ISSUE TITLE
what type of performance regression testing does GHC go through?

### ISSUE THREAD

**Issue by ketzacoatl** [ghc-proposals/ghc-proposals#410]
Hi,

Does the GHC release or development process include regression testing for performance?

Is this the place to discuss ideas for implementing such a thing and to eventually craft a proposal?

I believe the performance impact of changes to GHC needs to be verified/validated before release. I also believe this would be feasible if we tracked metrics on building a wide variety of real-world packages. Using real-world packages is one of the best ways to see the actual impact users will experience. It's also a great way to broaden the scope of tests, particularly with the combination of language pragmas and enabled features within the compiler.

**Comment by nomeata** [comment]
Thanks for your interest!

> Is this the place to discuss ideas for implementing such a thing and to eventually craft a proposal?

Probably, the https://mail.haskell.org/mailman/listinfo/ghc-devs mailing list is more appropriate. There are existing performance tracking efforts, see https://gitlab.haskell.org/ghc/ghc/-/wikis/building/running-tests/performance-tests for more information.

**Comment by goldfirere** [comment]
Just to echo @nomeata: I agree that the ghc-devs list is a better place for this kind of idea. A ghc-proposal is more about the user-facing interface of GHC, not about its internal processes. We have a good deal of performance testing as part of our CI infrastructure, though more might be better. I do think following the link @nomeata provided and/or following up on the mailing list will yield more information.

Please, do not take these redirections as a suggestion that this issue is not important! Both @nomeata and I care very much about performance of GHC and have taken concrete action to try to track and/or improve it.

Thanks for posting!

**Comment by tomjaguarpaw** [comment]
FWIW I just posted this question: https://mail.haskell.org/pipermail/ghc-devs/2021-March/019613.html
