### ISSUE TITLE
Pre-proposal: Undeprecate DatatypeContexts

### ISSUE THREAD

**Issue by noughtmare** [ghc-proposals/ghc-proposals#611]
For context see the discussion on discourse: https://discourse.haskell.org/t/datatypecontexts-has-something-changed-since-it-was-marked-deprecated/7560/7?u=jaror

I think deprecating DatatypeContexts was an overreaction to the realisation that it does not allow you to actually use the constraints. 

My main point is: even if DatatypeContexts only imposes restrictions, it is still useful to prevent accidentally writing malformed types.

## The deprecation of DatatypeContexts

The explanation of the decision to deprecate DatatypeContexts seems to be here: https://web.archive.org/web/20190518055322/https://prime.haskell.org/wiki/NoDatatypeContexts

> ## Summary
> 
> H98 and H2010 allow a context to be given for datatypes, e.g. the Eq a in
> ```haskell
> data Eq a => Foo a = Constr a
> ```
> This proposal is to remove support for that context.
> 
> ## Description
> 
> Datatype contexts (called "stupid theta" in GHC sources) appear, at first glance, to be very useful, but in actual fact they are not as useful as they seem.
> 
> One might expect that, with the above Foo type, one could write
> ```haskell
> isEq :: Foo a -> Foo a -> Bool
> isEq (Constr x) (Constr y) = x == y
> ```
> and the compiler would know that there is an Eq a instance from the datatype context. However, this is not the case. We instead must write
> ```haskell
> isEq :: Eq a => Foo a -> Foo a -> Bool
> isEq (Constr x) (Constr y) = x == y
> ```
> In fact, we cannot even write
> ```haskell
> getVal :: Foo a -> a
> getVal (Constr x) = x
> ```
> We must write
> ```haskell
> getVal :: Eq a => Foo a -> a
> getVal (Constr x) = x
> ```
> instead.
> 
> When we would expect the compiler to have the instance already available, in actual fact we have to provide it ourselves. The problem is that the constraint is not actually on the datatype, but rather, on the type of the constructor. Worse, the dictionary is not stored in the constructor, but simply discarded.

I think this is all one big misunderstanding about the use of the feature. And the trivial `Foo` example obscures the true reason `DatatypeContexts` are useful. 

## Wadler's original intention

The original intention of at least one author of Haskell98, Philip Wadler, was briefly mentioned in [this old mailing list thread](http://web.archive.org/web/20151208175102/http://code.haskell.org/~dons/haskell-1990-2000/threads.html#04062):

> The class constraints on data declarations were a simple way for the user to ask the compiler to enforce this invariant. They have compile-time effect only, no effect whatsoever on run-time (in particular, no dictionaries should be passed).

> Because my interest is as much in documentation as in constraints on
> how the program executes
> […]
> Your `redundant pollution’ is exactly the effect I want to achieve!

## Further explanation

These comments by Wadler are a bit succinct, so I will explain my interpretation of them in more detail using a simple `Set` type as a running example:

```haskell
data Eq a => Set a = MkSet [a]
```

The primary purpose of adding this constraint is to make it impossible to create a `Set a` where `a` does not have an `Eq` instance. I'd argue even just having that restriction by itself is useful.  This is also the point that @goldfirere makes in [his presentation about partial type constructors](https://www.youtube.com/watch?v=rqmCwpRXT_E) which seeks to make DatatypeContexts more useful. He uses the example of a plainly wrong type:

```haskell
x :: [Maybe]
x = []
```

Clearly `Maybe` needs another type parameter. As long as we only use the empty list we won't run into any issues, but still we reject this definition.

And explains that we should treat sets of functions similarly:

```haskell
y :: Set (Int -> Int)
y = MkSet []
```

That should be treated the same way. The `Int -> Int` type has no `Eq` instance, so even the thought of creating such a set should be rejected.

TODO: expand this explanation

## Wrinkle 1: DatatypeContexts needs to reject more

In the discourse discussion @AntC2 points out:

> One of the current rules for DatatypeContexts is not to apply the constraint for constructors that don’t mention that type param. (Yeah my description is baffling – even to me. [And demonstrated in the docos with NilSet](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/datatype_contexts.html), but not explained. Better shown with an example, let’s try for a BST):
> ```haskell
> data Ord a => Set a = Tip  |  Node (Set a) a (Set a)
> ```
> So an empty Set consisting of only a Tip gets no constraint demanded. But, but! For Tip there’s no mention of a only because that’s a H98 style decl. I know really Tip :: Set a (to use GADT style) so its type does mention a.
> 
> Then while I was hacking Hugs, I dropped the “that don’t mention that type param” part of the rule. So I get Tip :: Ord a => Set a/no need for a empty separate function.

I would like GHC to make the same change.

And @goldfirere explains in his presentation that DatatypeContexts doesn't catch all problems, e.g. this is not rejected:

```haskell
idSet :: Set a -> Set a
idSet x = x
```

I think it is relatively easy to add some logic to GHC to require an `Eq` constraint whenever `Set` is mentioned in any type.

## Wrinkle 2: Optimising unused constraints away

Adding a datatype context to a type like `Set` would mean that you'd have to write:

```haskell
empty :: Ord a => Set a
empty = Tip
```

GHC will compile this to a function under the hood:

```haskell
empty = \@a _ordDict -> Tip @a 
```

This could add a slight bit of of overhead. I don't know how significant that is. Benchmarks are needed.

**Comment by noughtmare** [comment]
I think types with contexts should necessary be abstract, because the only reason to add a context is to ensure an invariant can always be maintained. For example, the `Set` type would have an `Ord` context *because* it needs to maintain the ordering invariant.

I could manually try to make sure all functions in my public interface have proper `Ord` constraints, but why not let the compiler help me with that?

Pattern synonyms are an option, but I'd argue those are more complicated than data type contexts. And they cannot prevent malformed types like this:

```haskell
idSet :: Set a -> Set a
idSet x = x
```

**Comment by tomjaguarpaw** [comment]
> For example, the `Set` type would have an `Ord` context because it needs to maintain the ordering invariant.
>
> I could manually try to make sure all functions in my public interface have proper Ord constraints, but why not let the compiler help me with that?

But when it maintains that invariant, using `Ord` operations, it automatically picks up that constraint, and when it picks up that constraint, it was needed. So it seems to be the constraint is present on public API functions if and only if it is needed, which seems like exactly what we would want.

Put another way, I still don't see why we would want an `Ord` constraint on `empty :: Set a`. I don't understand why that's useful.

**Comment by phadej** [comment]
`Set (Int -> Int)` type is not malformed. It may not have values, but it's a valid type. It's the same to say that `Void` is malformed.

```haskell
{-# LANGUAGE DatatypeContexts #-}
data Ord a => OrdBox a = MkOrdBox a

id' :: OrdBox (Int -> Int) -> OrdBox (Int -> Int)
id' = id
```

**is accepted** by GHC-7.0.2 for example.

**Comment by noughtmare** [comment]
> Set (Int -> Int) type is not malformed.

> Put another way, I still don't see why we would want an Ord constraint on empty :: Set a. I don't understand why that's useful.

See section 2.2 of [Partial type constructors: or, making ad hoc datatypes less ad hoc](https://dl.acm.org/doi/10.1145/3371108)


> is accepted by GHC-7.0.2 for example.

Yes, that's why I put in wrinkle 2, we need to change DatatypeContexts to reject more programs.

> but that's something completely different than what DatatypeContexts was.

Fair enough, perhaps I should present this proposal differently.

**Comment by AntC2** [comment]
> I think it is relatively easy to add some logic to GHC to require an `Eq` constraint whenever `Set` is mentioned in any type.

(This comment wrt `idSet x = x`, which doesn't mention any data constructor.)

I think:

1. That won't be easy to implement at all. Because currently the implementation all hangs around the data constructor/ doesn't apply at the type level. But that doesn't matter because
3. I disagree with that rule/I'm disagreeing with @goldfirere: for that definition of `idSet`, _don't_ require the constraint. Whatever built the `Set` -- using the data constr -- saw the constraint, we've no need to ask for it again.

(This is pretty much the argument SPJ tried to run in 1999. I'm agreeing; I think Wadler was wrong.)

**Comment by noughtmare** [comment]
> 2. I disagree with that rule

I don't quite understand why. If you accept that the type `Set (Int -> Int)` is malformed, then it should be rejected regardless of whether it is constructed or used in any other way. If you think the type itself is not a problem, then I don't see why you would want to reject its construction.

I guess a practical reason is that you otherwise couldn't implement `Foldable Set`, but I can't really connect that to a conceptual explanation.

Also, if we have a mechanism to constrain only the construction then we should dually provide a mechanism to constrain only the destruction in my opinion. Especially because our data types are also codata types in Haskell.

**Comment by AntC2** [comment]
> I guess a practical reason is that you otherwise couldn't implement Foldable Set, 

Exactly. Not just `Foldable` but mountains of constructor classes. We're already excluded from `Functor`, because it wants to build the type but we've no way to pass in the constraint to the constructor. If you're going to insist on the constraint even to destruct the type, that's going to exclude far too much.

Supporting `DatatypeContexts` at the type level (without deriving it from the appearance of data constructors) isn't anything the extension used to do. So that isn't merely 'undeprecating', it's more like starting again. 

Historical aside: Haskell 1990 included wanting contexts on type synonyms:

```
type Floating a => Cartesian a = (a, a)
```

But nobody could figure out how to implement that (where/how would you supply a dictionary?); so it was dropped in Haskell 1991. (Note this was before anybody dreamed up `newtype`s.)

I'm not sure what you're wanting is much different.

>  If you accept that the type Set (Int -> Int) is malformed ...

Wee-ell I don't like it. But I'm reasonably relaxed that its only possible value is an empty `Set` (or `undefined`). Those uglies are ubiquitous. It's in the same pile of muck as Haskell not detecting divide by zero or fixed-width numeric overflow.

**Comment by noughtmare** [comment]
> I'm not sure what you're wanting is much different.

For one, I don't intend to require any dictionary passing anywhere. I basically just want to extend the kind checker to make sure all constrained type constructors are accompanied by their corresponding constraints. 

Essentially the kind checker would do the following:

1. when checking a top-level or higher rank type: 
2. add all constraints to a local environment
3. kind check like normal until you encounter a constrained type constructor
4. make sure that the corresponding constraint is in the local environment or in the global list of instances
5. continue like normal

I haven't yet thought about taking into account constraint polymorphism and quantified constraints. That could complicate things.

**Comment by Ericson2314** [comment]
I think it would be better to wait bring this back for "promoted constraints", which would be useful for deprecating replacing type families with something that requires evidence, which would avoid a bunch of annoyances with type families have today.

**Comment by monoidal** [comment]
Constructors can be partially applied. For example:

```hs
newtype T a b = MkT (a b)
newtype R a b = MkR (a Int)
f :: T Set a
g :: R Set a
h :: p Set a
```

Presumably you'd like the constraint `Eq a` for `f` but not `g`, and what about `h` where we can replace `p` either by `T` or `R`? I don't think it's as simple as in https://github.com/ghc-proposals/ghc-proposals/issues/611#issuecomment-1715951206. The paper "Partial Type Constructors" introduces a new form of constraint `p @ x`.

**Comment by noughtmare** [comment]
> Constructors can be partially applied. 

That does indeed seem very difficult to solve. We could conservatively reject, but that does not seem very reasonable.

> The paper "Partial Type Constructors" introduces a new form of constraint p @ x.

Yeah, I think the problem of that is that it adds constraints everywhere which I expect to have a large compile-time and run-time overhead.

**Comment by noughtmare** [comment]
@Ericson2314 

> I think it would be better to wait bring this back for "promoted constraints"

Do you have a link for this, I don't know what promoted constraints would be but they sound interesting.

**Comment by AntC2** [comment]
> Constructors can be partially applied.

(Meaning type constructors.) Thank you @monoidal, that's what I'd call a slam dunk argument to continue `DatatypeContexts`  (or something like it) working via data constructors only: those can be partially applied/passed as arguments/be the result of a function/etc, and take their constraints with them.

And the semantics for data constructors can be sensitive to whether they appear in a pattern match (deconstruct) or an expression (build) context -- as GHC is already sensitive to for `PatternSynonyms` and `GADT` constructors. Note that for a pattern match you must use the literal upper-case data constructor/not partially applied/passed as a variable/etc. I get it @noughtmare's Proto-proposal doesn't want that sensitivity as to context. GHC pre-1999 did implement that; and that's the behaviour I'd like to get back to.

> The paper "Partial Type Constructors" introduces a new form of constraint `p @ x`.

Yes, and that seems the principled way to deal with partially applied type constructors. To my mind that comes with a large amount of machinery and annoyances, so I'm sceptical. And because it applies at the type level not data-constructor, I don't see it as some form of the `DatatypeContexts` feature (but this is just quibbling over semantics).

More critically, I don't see how `p @ x` can distinguish a type appearing in a pattern-match/deconstruct position vs. an expression/build position. And the paper doesn't try for that -- which means raising constraints even where the code is merely deconstructing the type in order to build some other type (as with `fmap`) -- which seems just useless clutter/bookkeeping.

**Comment by AntC2** [comment]
> the semantics for data constructors can be sensitive to whether they appear in a pattern match (deconstruct) or an expression (build) context

(Another) historical note. "in [this old mailing list thread](http://web.archive.org/web/20151208175102/http://code.haskell.org/~dons/haskell-1990-2000/threads.html#04062)" the proposal quotes as 'Wadler's original intention', the following message is from Mark P Jones re implementation in Hugs:

> Arranging for constraints that appear in the types of constructors to show up whenever that constructor is used --- whether in an application or a pattern match --- was not at all tricky.  Indeed, it seems very natural, and Hugs uses exactly the same code to deal with the two cases.

Hmm. I can read that code -- or at least as it was left in 2006. Yes it's copy-pasted code; no it's not 'the same' code: "it seems very natural" to leave the code as is in the expression/build routines, but suppress it in the pattern-match routines -- and that's what I've done. Because I wanted to support `foldMap` and friends over a `Set` built with an `Ord a` constraint.

I'm very happy to trial -- indeed please do volunteer -- any amount of evil code you think might break something with this behaviour.

**Comment by uhbif19** [comment]
I am very much in support of this. But it seems hopeless to me so far, cuz seems like 

Widely suggested GADT/existential alternative:

1. has different semantics, storing class instance
2. breaks deriving, by forcing you to write standalone deriving boilerplate

**Comment by fxdpntthm** [comment]
The follow up work of [1] is [2]. It agrees that we should not deprecate `DatatypeContexts`, rather give it the semantics that it deserves. I implemented [3] it in GHC last year and found no major annoyances apart from Functor-Applicative-Monad typeclass hierarchy to break. The paper discusses some options after arguing what does it even mean to have a Partial Applicative as what `ghc-base` currently has? 

[1]: https://dl.acm.org/doi/10.1145/3371108
[2]: https://dl.acm.org/doi/10.1145/3546189.3549923
[3]: https://github.com/iafP/ghc

**Comment by noughtmare** [comment]
The idea I tried to propose here was not workable due to the fact that type constructors can be partially applied, which requires more research and may be impossible to do efficiently. Do, I'm closing this issue. Feel free to discuss other related proposals in new issues.
