### ISSUE TITLE
Allow Trailing Comma in List Constructor Syntax

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [ghc-proposals/ghc-proposals#653]
It is useful to be able to quickly reorder or append to lists with one element per line. For example

```text
[
  1,
  3,
  2,
]
-- to
[
  1,
  2,
  3,
]
```

Currently, if the last line is to be moved, a comma must be placed after it and the new last line must have the comma removed. If appending, a comma must be added to the previous last line.

These comma changes make it annoying to change lists and make diffs more cluttered. As evidence of the trailing commas utility many other languages implement it like c, Java and JS, and Python. Also, even Haskell language designers have acknowledged the utility of the trailing comma by allowing it in module exports and imports.

**Comment by JakobBruenker** [comment]
Note that the [ExtraCommas proposal](https://github.com/ghc-proposals/ghc-proposals/pull/87) exists, which was sort of accepted, though on the condition of minor changes being done, which didn't happen, so it effectively lost its accepted status. But I imagine taking up that proposal again could be done.

**Comment by int-index** [comment]
In the ExtraCommas proposal, if you read the discussion, you can see that I was one of its main opponents. I didn't like the fact that `[a,b,c,]` would be allowed but `(a,b,c,)` wouldn't, because tuples and lists are rather similar. And if we allowed extra commas in tuples, that'd be in conflict with `TupleSections`.

While I still think this inconsistency is rather ugly, one thing that changed is that I don't care to the same extent. If `ExtraCommas` would only work with lists but not with tuples, so be it. Not the hill that I want to die on.

So if anyone wants to revive that proposal, you'll probably see less resistance to it, therefore the chances of getting it accepted will be higher.

**Comment by BebeSparkelSparkel** [comment]
@int-index I just want a trailing list comma, the ambitious alternatives are something entirely different that deserve their own proposal since they are changing so much.

The argument made by @gbaz *[an n-tuple is absolutely different than an n+1-tuple or an n-1 tuple, but a list of n elements is effectively the same as a list of n+1 or n-1 elements](https://github.com/ghc-proposals/ghc-proposals/pull/87#issuecomment-343372329)* was very apt and currently there is no `ListSections` and `snoc [a,b,c]` is succinct and more clear than the [a,b,c,] append.

**Comment by BebeSparkelSparkel** [comment]
@JakobBruenker Thanks for the link. The scope of that proposal seemed to explode, which could have been the problem.

**Comment by JakobBruenker** [comment]
How do you feel about leading commas?

In my view it would make a lot of sense, since it both provides consistency and caters to the rather common pattern in Haskell code where commas are written at the beginning of the line, as in
```haskell
[
, 1
, 2
, 3
]
```

**Comment by BebeSparkelSparkel** [comment]
Leading commas are not already in haskell's cannon. They were not added to imports and exports and thus should be in their own proposal since that was probably discussed and ultimately rejected somewhere.

**Comment by JakobBruenker** [comment]
> since that was probably discussed and ultimately rejected somewhere.

Well, it was indeed discussed - in the proposal I mentioned above - but it was accepted rather than rejected before the proposal went dormant.

I'm guessing the reason that trailing commas - but not leading commas - were made part of the export list in Haskell 98 is because the style I hinted at was not commonplace 25 years ago.

**Comment by BebeSparkelSparkel** [comment]
To keep things simple I'm only willing to propose leading or trailing.

Leading merits
- nice alignment
- easy visual comma completeness
- only one acceptable indentation scheme instead of 2

Trailing merits
- Copy Paste compatibility with other language data lists

```haskell
-- current
c0 =
  [ 1
  , 2
  ]
c1 = [
    1
  , 2
  ]
c2 = [
    1,
    2
  ]
c3 = [
  1,
  2
  ]
c4 = [
  1,
  2]

-- leading comma
l0 = [
  , 1
  , 2
  ]
l1 =
  [
  , 1
  , 2
  ]

-- trailing comma
t0 = [
  1,
  2,
  ]
t1 = [
    1,
    2,
  ]
t2 =
  [
    1,
    2,
  ]
```

After looking at this it seems like leading commas have more merrit and should probably be the way to go. If you think so as well, I'll switch this to leading commas.

**Comment by JakobBruenker** [comment]
Hmm well I can tell you that personally, I'd use leading commas more, but I don't know how this would apply to other users. If you're set on only doing one it might make sense to do a quick poll in one (or more) of the Haskell discussion fora like discourse or reddit.

**Comment by tomjaguarpaw** [comment]
If this feature does not support trailing commas then this rules out Ormolu users from benefitting from it.

**Comment by BebeSparkelSparkel** [comment]
Seems that trailing commas is already cannon. I will stick with trailing.

**Comment by Tritlo** [comment]
I wish leading commas were canon, but seeing as they are not, I am in favor of the trailing commas.

**Comment by AntC2** [comment]
What annoys me most about list syntax:

```
[1,3,5,7]   -- square brackets means a list
[1,3 .. 7]  -- same list, square brackets, only one comma allowed
[1,3 .. ]   -- infinite list, square brackets
[1 .. ]     -- infinite list, square brackets
(x:xs)      -- pattern to match any of the above, can't use commas, can't use square brackets
```

Is it beyond Haskellers to find a way to use [something inside] square brackets for pattern matching a list?

**Comment by tomjaguarpaw** [comment]
> Is it beyond Haskellers to find a way to use [something inside] square brackets for pattern matching a list?

You can do that:

```.hs
ghci> case [1,2,3] of [1,2,3] -> "OK!"
"OK!"
```

**Comment by BebeSparkelSparkel** [comment]
@AntC2 That is irrelevant to this proposal.

**Comment by AntC2** [comment]
> allowing it in module exports and imports.

Although we call those "lists", they're actually sets, so relative order of the elements doesn't matter.

> It is useful to be able to quickly reorder or append to lists with one element per line.

TBH I don't think I've ever wanted to put a long list of literal values in a program, let alone chop them about. (`String`s are lists, but I'm not including them, because you wouldn't go to the bother of comma seps between the `Char`.) Why is order so important to you you want to track diffs?

I know Haskell/functional languages/LISP have a long history of using lists/taking them as examples to teach newbies; but they're almost always a terrible choice for industrial code. If you're often wanting to "reorder or append" and then see the change in diffs, doesn't that show a list is a poor fit to the requirements? Use a `Set` or a `Hashmap` or some sort of indexed structure.

I do use Lists to represent a generated series (say of closer approximations/Newton-Raphson), but that doesn't need a long bunch of literals as a starter.

Is there something bigly wrong with:

```
    lComma =    [ "first"
                , "second"
                , "last"
                ]
```



> Seems that trailing commas is already cannon.

I don't think there's a canon. In `do` blocks (where certainly reordering does need tracking) the more usual canon is layout -- but if you want an explicit separator:

```
    do  {
        ; firststep
        ; secondstep
        ;                 -- bit of comment
        ; nextstep
        ;                 -- space for more
        }

```

**Comment by BebeSparkelSparkel** [comment]
@AntC2 Please review https://github.com/ghc-proposals/ghc-proposals/pull/87

Many want this feature and thus have uses for them.

**Comment by AntC2** [comment]
> Please review #87

Gives me a 404. Or do you want me to read >200 comments? -- many of which seem to be off-topic or contradictory or both, BTW.

I repeat: import/export so-called "lists" are sets. The comments I skimmed seem to be as much about `TupleSections` as anything.

If there's a slam-dunk motivation for your proposal here -- specifically for the insides of `[    ]`, why's it so hard to state it? You'll need to state it if you want to turn this into a proposal. All I see so far is matters of opinion: "useful", "annoying", " like c, Java and JS, and Python.". 'Make Haskell more like language X' is what I'd call negative motivation: I prefer Haskell because it's not those languages.

**Comment by BebeSparkelSparkel** [comment]
@AntC2 I have already put as much effort in this as I am going to.

- Many others want this feature
- This exact feature has already been approved in a previous proposal

If you personally don't want it, state it, but that is a minority opinion here from what I have seen so far.

**Comment by JakobBruenker** [comment]
@ad-si has created a proposal that addresses this at https://github.com/ghc-proposals/ghc-proposals/pull/658

**Comment by BebeSparkelSparkel** [comment]
deffering to #658
