### ISSUE TITLE
Debug typeclass for showing values without Show

### ISSUE THREAD

**Issue by brandonchinn178** [ghc-proposals/ghc-proposals#662]
I couldn't find any discussions around this, so creating an issue to test the waters.

It's often the case for newcomers to want to print a value after forgetting to derive Show. It could also be useful for test frameworks to be able to Show values whether or not they have a Show instance. I just learned about the `:force` command in ghci, and was wondering if there was a way to expose it in normal Haskell code.

What are the downsides of providing a built-in Debug typeclass that's automatically derived like Typeable? Then you can drop in a `debugShow` anytime you want to view a value, which renders it the same as `:force`.

**Comment by tomjaguarpaw** [comment]
> What are the downsides of providing a built-in Debug typeclass that's automatically derived like Typeable?

It breaks encapsulation for a start. Now, if I want to hide my internals from consumers I have to somehow suppress or alter the `Debug` instance. In return I get the benefit of forgetting to derive `Show`. It doesn't seem like a worthwhile trade-off to me.

Shouldn't we just be reminding newcomers to derive `Show`?

**Comment by JakobBruenker** [comment]
Note that `recover-rtti` has a function [`anythingToString :: forall a. a -> String`](https://hackage.haskell.org/package/recover-rtti-0.5.0/docs/Debug-RecoverRTTI.html#v:anythingToString), e.g.

```haskell
ghci> data A = MkA Int
ghci> anythingToString (MkA 24)
"MkA 24"
```

Admittedly newcomers are unlikely to know about it though.

**Comment by brandonchinn178** [comment]
@tomjaguarpaw Yes, we should be telling newcomers to just use Show. But my immediate issue is wanting to show any value in a test framework. Which @JakobBruenker's link provides, so I could just use that. Didn't know you could do this in pure Haskell (admittedly with a lot of unsafe coerces)!

**Comment by googleson78** [comment]
I have another use case that Show *almost* works for, but annoyingly not quite, which is that I would love to have some way always to be able to say "show me how I need to enter this value into a Haskell source file so that I get the same value that is currently being represented.

> Shouldn't we just be reminding newcomers to derive Show?

The reason why `Show` doesn't work for that is that you can define your own `Show` instances, and some really base things like `UTCTime` do that, which we can only change with some huge effort.

Given, maybe this is not something we want to strive for with `Show`, but I would enjoy having *some* official way to do this.

> It breaks encapsulation for a start. Now, if I want to hide my internals from consumers I have to somehow suppress or alter the Debug instance.

But consumers who want to use your library as intended are not going to reach for the hypothetical `Debug` class as a means of serialising some internal values into their Haskell programs, or relying upon. I'd assume this would be marked as a tool not to be used outside of debugging and/or logging, like `trace*`. 

The "you can't reach for my internals ever under any circumstances" ship has also somewhat already sailed, because you can look at non-exported things from `ghci`, although that's definitely not the same thing as accessing them from normal code.

**Comment by tek** [comment]
I'd love this for GHC types – when you want to know which constructor of `HsType` or something a value has in addition to its contents, you have to write some boilerplate, because there are no `Show` instances and `Outputable` just prints human readable representations.
Since many of those types are huge, it would also be useful to control the nesting level that should be printed, like Nix's `traceSeqN`, so fields beyond that are ellipsized.

**Comment by JakobBruenker** [comment]
@tek Conveniently, all of the types in the GHC AST have a `Data` instance, so you can use [`gshow`](https://hackage.haskell.org/package/syb-0.7.2.1/docs/Data-Generics-Text.html#v:gshow)

**Comment by googleson78** [comment]
I'm sure you can implement that via `Generic` as well as `Data`, but those are not always available. And sometimes for good reason - having a `Generic` really does mean "here, my internals are open for all to see", because you are indeed expected to use `Generic` and `Data` in "normal business logic" code, imo, as opposed to having some technique which is explicitly tagged as "only use this for debugging or logging".

**Comment by tomjaguarpaw** [comment]
But your use case is

> show me how I need to enter this value into a Haskell source file so that I get the same value that is currently being represented

If you can construct arbitrary values, aren't we already assuming that the internals are already open for all to see?

**Comment by sgraf812** [comment]
I think there are two different use cases:

1. One is to have a function that can show debug output for any boxed heap value whatsoever, without having a `Show`/`Generic`/`Data` instance whatsoever. IMO the perfect solution here is `recover-rtti`, as proposed here https://github.com/ghc-proposals/ghc-proposals/issues/662#issuecomment-2195509010.
2. A different use case is to *know* the static type of a value, and then generate Haskell syntax that constructs said value, also without requiring any type class instance. I think you can just use Template Haskell for that. Specifically, [`lift`](https://hackage.haskell.org/package/template-haskell-2.22.0.0/docs/Language-Haskell-TH-Syntax.html#v:lift) is exactly that function. If your type does not have a `Lift` instance, you can use [`makeLift` from the `th-lift` package](https://hackage.haskell.org/package/th-lift-0.8.4/docs/Language-Haskell-TH-Lift.html#v:makeLift).

Example for (2):

```
$ ghci -XTemplateHaskell -package template-haskell -package th-lift
ghci> import Language.Haskell.TH
ghci> import Language.Haskell.TH.Lift
ghci> import Language.Haskell.TH.Ppr
ghci> data T = MkT [(Int, Bool)]
ghci> bigT = MkT [(1,True),(2132,False)]
ghci> reprT :: Quote m => T -> m String; reprT t = do e <- $(makeLift ''T) t; return (pprint e)
ghci> reprT bigT :: IO String
"Ghci1.MkT [(1, GHC.Types.True), (2132, GHC.Types.False)]"
```

This works well in the shell where the stage restriction is not as restrictive (we can use `reprT` immediately after having defining it).
